# Generated by Django 5.0.2 on 2024-03-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0034_remove_order1_order_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='PUNTOS',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
