# Generated by Django 5.0.2 on 2024-03-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0035_customuser_puntos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='PUNTOS',
        ),
    ]
