# Generated by Django 5.0.2 on 2024-03-18 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0037_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
